---
- name: Downloading service dependencies  # Name of the task
  shell: go get {{ dependencies }}  # Get all service dependencies

- name: Installing service          # Name of the task
  shell: go install calc-service    # Installing Go service

- name: Running service             # Name of the task
  command: calc-service             # Execute service
  args:
    chdir: $GO_PATH/bin/            # from go/bin directory
